config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }, skip: ['passwords', 'sessions', 'registrations']

  devise_scope :user do
    delete '/users/log_out', to: 'devise/sessions#destroy',
                             as: :destroy_user_session
  end

  authenticated :user do
    root 'dashboard#show', as: :authenticated_user
  end

  root 'high_voltage/pages#show', id: 'home'

  resources :users, only: [] do
    resources :repositories, only: [:create, :show, :destroy]
  end

  get '/repositories/search', to: 'repositories#search'
  resources :repositories, only: [:index] do
    resources :builds
  end
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  belongs_to :user
  has_many :builds, dependent: :destroy

  validates :name, :clone_url, presence: true, uniqueness: true
  validate :check_eligibility

  paginates_per 5

  # Put cloning into the queue to avoid long wait times.
  # after_create { self.delay.clone }

  QUEUED = 0
  IN_PROGRESS = 1
  COMPLETE = 2
  ERROR = 3

  def octokit_client
    id = ENV.fetch('GITHUB_CLIENT_ID')
    secret = ENV.fetch('GITHUB_CLIENT_SECRET')
    client = Octokit::Client.new(client_id: id, client_secret: secret)
  end

  def github_url
    self.clone_url.gsub('.git', '')
  end

  def working_directory
    cwd = Rails.root.join('tmp', name)
    # Clone it.
    self.clone
    cwd
  end

  def cloned?
    self.clone_status == COMPLETE && Dir.exist?(working_directory)
  end

  def re_clone
    self.update_column(:clone_status, QUEUED)
    self.delay.clone
  end

  def clone
    cwd = Rails.root.join('tmp', name)
    if Dir.exist?(cwd) && Dir.exist?(File.join(cwd, '.git'))
      self.update_column(:clone_status, COMPLETE)
      #send_clone_status('success', "Repository #{self.name} is ready!")
    else
      FileUtils.mkdir_p(cwd)

      Dir.chdir(cwd) do
        self.update_column(:clone_status, IN_PROGRESS)
        send_clone_status('cloning', 'Cloning repository into...')
        response = system("git clone --depth 1 #{clone_url} .")

        if response
          self.update_column(:clone_status, COMPLETE)
          status = 'success'
          message = "Repository #{self.name} is ready!"
        else
          self.update_column(:clone_status, ERROR)
          status = 'error'
          message = "An error occurred while cloning #{self.name}."
        end
        send_clone_status(status, message)
      end
    end
  end

  def specs?
    spec_list.any?
  end

  def spec_list
    @spec_list = []

    filepath = working_directory
    if File.directory?(File.join(filepath, 'spec'))
      Dir.chdir(filepath) do
        @spec_list = Dir.glob('spec/**/*_spec.rb')
      end
    end

    @spec_list
  end

  def class_list
    convert_files_to_class_list(spec_list)
  end

  def rails_app?
    gemfile = File.join(working_directory, 'Gemfile')
    @rails ||= system(%{grep -q rails #{gemfile}})
  end

  def set_github_details
    gh = octokit_client.repo(name)

    unless gh.language == 'Ruby'
      errors.add(:repository, 'must be a Ruby application.')
    end

    attributes = {
      clone_url: gh.clone_url,
    }

    assign_attributes(attributes)
  rescue Octokit::NotFound
    errors.add(:repository, 'cannot be located on GitHub.')
  end

  def send_clone_status(status, message)
    # Send Pusher on status/value changes
    begin
      hash = {
        id: self.id,
        status: status,
        status_text: message,
        url: "/repositories/#{self.id}",
      }
      Pusher.trigger('status_channel', 'client-repository-status', hash)
    rescue Pusher::Error => e
      # (Pusher::AuthenticationError, Pusher::HTTPError, or Pusher::Error)
    end
  end

  def namespace
    return nil if rails_app?

    unless @namespace
      gemspec_file = Dir.glob(File.join(working_directory, "*.gemspec")).first
      @namespace = ''

      if gemspec_file
        contents = File.read(gemspec_file)
        if contents =~ /version\s*=\s*(\w+)::VERSION/
          @namespace = $1
        else
          # try gemspec filename
          @namespace = File.basename(gemspec_file).gsub('.gemspec', '')
        end
      end
    end
    @namespace
  end

  def convert_files_to_class_list(file_list)
    class_name_list = []
    if file_list.is_a?(Array)
      class_name_list = file_list.map do |s|
        matches = s.match(%r{spec\/(?:lib\/|unit\/)?([\w\/]*)_spec.rb})
        if matches.present?
          tokens = matches[1].split('/')
          # Exclude common folders
          if rails_app?
            if ['features', 'requests', 'routing', 'views'].include?(tokens.first)
              nil
            elsif ['models', 'controllers', 'helpers', 'mailers'].include?(tokens.first)
              tokens.shift
            end
          elsif namespace.present? && tokens.first != namespace
            # Watch out for case sensitivity issues.
            if tokens.first.downcase == namespace.downcase
              tokens[0] = namespace
            else
              tokens.unshift(namespace)
            end
          end
          tokens.map(&:camelize).join('::')
        end
      end.compact
    end

    class_name_list
  end

  def check_eligibility
    gh = octokit_client.repo(name)

    unless gh.language == 'Ruby'
      errors.add(:repository, 'must be a Ruby application.')
      return false
    end

    begin
      octokit_client.contents(name, path: 'spec')
    rescue Octokit::NotFound
      errors.add(:repository, 'must use RSpec and have a spec folder.')
    end
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_filter :redirect_to_existing_repository, only: :create
  before_filter :load_repository, only: [:show, :destroy]

  def create
    @repository = current_user.repositories.new(repository_params)
    @repository.set_github_details

    if @repository.save
      flash[:notice] = "#{@repository.name} has been added."
      redirect_to [@repository.user, @repository]
    else
      flash[:error] = @repository.errors.full_messages.first
      redirect_to root_path
    end
  end

  def show
    @repo = Repository.find(params[:id])
    # @gh_repo = @repo.github_repo
    @builds = @repo.builds.order('created_at desc')

    @spec_list = @repo.class_list
    @spec_list_tag_str = @spec_list.join(',')
    add_breadcrumb(@repo.name)
  end

  def search
    id = ENV.fetch('GITHUB_CLIENT_ID')
    secret = ENV.fetch('GITHUB_CLIENT_SECRET')
    client = Octokit::Client.new(client_id: id, client_secret: secret)
    render json: client.search_repositories(params[:term]).items.map(&:full_name)
  end

  def destroy
    if @repository.destroy
      flash[:notice] = "We've deleted #{@repository.name}"
      redirect_to root_path
    else
      flash[:error] = "Aw snap! We couldn't delete that repo."
      redirect_to @repository
    end
  end

  def index
    search = Repository.ransack(name_cont: params[:search])
    @repositories = search.result.page(params[:page])
  end

  private

  def redirect_to_existing_repository
    repository = Repository.find_by_name(params[:repository][:name])
    redirect_to [repository.user, repository] if repository
  end

  def load_repository
    @repository = Repository.find(params[:id])
  end

  def repository_params
    params.require(:repository).permit(:name)
  end
end

app/views/repositories/_add_new_modal.html.slim
#addNewRepoModal.modal.fade[tabindex="-1" role="dialog"]
  .modal-dialog[role="document"]
    .modal-content
      .modal-header
        button.close[type="button" data-dismiss="modal" aria-label="Close"]
          span[aria-hidden="true"]
            | ×
        h4.modal-title
          | Add Open Source Repo
      = form_for [current_user, Repository.new] do |f|
        .modal-body
          .form-group
            = f.label "GitHub repo name"
            = f.text_field :name, placeholder: "jheth/rumble-specs", class: "typeahead form-control"
        .modal-footer
          button.btn.btn-default[type="button" data-dismiss="modal"]
            | Close
          = f.submit "Add Repo", class: "btn btn-primary"

app/views/repositories/_build_card.html.slim
div id="build-#{build.id}" class="row #{build.status_text}"
  .col-md-1
    = link_to(build.id, repository_build_path(build.repository, build))
  .col-md-5.sha
    - if build.last_sha
      = build.last_sha
    - else
      ' Pending...
      i.fa.fa-icon.fa-cog.fa-spin

  .col-md-1.status
    | #{build.status_text}
  .col-md-2
    | #{build.user.name}
  .col-md-3
    | #{build.created_at}

app/views/repositories/index.html.slim
.page-header
  h3
    => icon("github")
    ' Public Repositories
    small Open Source
  = render partial: "shared/basic_search_form", locals: { search_path: repositories_path }
.page-content
  - @repositories.each do |repository|
    .panel.panel-default
      .panel-body
        = link_to [repository.user, repository], class: "pull-left" do
          h4 = repository.name
  = paginate @repositories

app/views/repositories/show.html.slim
.breadcrumbs
  = render_breadcrumbs

.page-header.clearfix
  .pull-left
    h2 style="margin-top: 0;" = @repo.name
    h4
      a href="#{@repo.github_url}" target="_blank"
        = @repo.github_url
  .pull-right
    br
    - if @repo.cloned?
      = form_for([@repo, Build.new], url: repository_builds_path(@repo), remote: true) do |f|
        .spec-list-container.clearfix
          select class="select2-search__field" multiple="multiple" style="width: 500px" name="class_names[]"
            - @spec_list.each do |name|
              option value="#{name}" = name
          ' &nbsp;&nbsp;
          = f.submit "Build Now", class: "btn btn-primary"
        input type="checkbox" name="fail_fast" &nbsp;Quicky Mode (Stop on first failure)

    - else
      h4 class="cloning-repo-#{@repo.id}"
        | We're still cloning the repo... give us another minute.


- if @repo.cloned?
  h2 Builds
  ul.builds
    - @builds.each do |build|
      = render "build_card", build: build

javascript:
  $(document).ready(function() {
    $(".select2-search__field").select2({
      placeholder: 'Search Objects to Mutate',
      maximumSelectionSize: 4
    });
  });

= render 'shared/pusher'